---
vagrant:
  synced_folders:
    - host: "/Users/lauriekaptein/Sites/training/htdocs"
      guest: /var/www/training/htdocs
      type: nfs
    - host: "/Users/lauriekaptein/Google Drive/LimoenGroen/Projecten/drush/aliases"
      guest: /etc/drush
ansible:
  reroute_email: laurie@limoengroen.nl
