filebeat:
  prospectors:
    -
      paths:
        - /var/log/syslog
        - /var/log/auth.log
      input_type: log
      document_type: syslog

    -
      paths:
        - /var/log/apache2/*error*.log
      input_type: log
      document_type: apache

    -
      paths:
        - /var/log/drupal/*.log
      input_type: log
      document_type: drupal

  registry_file: /var/lib/filebeat/registry

output:
  logstash:
    hosts: ["logs.limoengroen.nl:5044"]
    tls:
      certificate_authorities: ["/etc/pki/tls/certs/logstash-forwarder.crt"]

shipper:

logging:
  files:
    rotateeverybytes: 10485760 # = 10MB