wizzlern_webservice.web_scraper.*:
  type: config_entity
  label: 'Web scraper config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
